<html>
  <head>
    <meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>Civil3D API定义多视图快（Multiview Block） | Gridea</title>
<link rel="shortcut icon" href="https://xiaoxiong314.github.io/favicon.ico?v=1600178709560">
<link href="https://cdn.jsdelivr.net/npm/remixicon@2.3.0/fonts/remixicon.css" rel="stylesheet">
<link rel="stylesheet" href="https://xiaoxiong314.github.io/styles/main.css">
<link rel="alternate" type="application/atom+xml" title="Civil3D API定义多视图快（Multiview Block） | Gridea - Atom Feed" href="https://xiaoxiong314.github.io/atom.xml">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Droid+Serif:400,700">



    <meta name="description" content="Multiview Block是Autocad Architecture中的概念。
[CommandMethod(&quot;DEFINEMVBLOCK&quot;)]
public void DefineMVBlock()
{
	Docu..." />
    <meta name="keywords" content="" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.10.0/katex.min.css">
    <script src="https://cdn.bootcss.com/highlight.js/9.12.0/highlight.min.js"></script>
  </head>
  <body>
    <div class="main">
      <div class="main-content">
        <div class="site-header">
  <a href="https://xiaoxiong314.github.io">
  <img class="avatar" src="https://xiaoxiong314.github.io/images/avatar.png?v=1600178709560" alt="">
  </a>
  <h1 class="site-title">
    Gridea
  </h1>
  <p class="site-description">
    温故而知新
  </p>
  <div class="menu-container">
    
      
        <a href="/" class="menu">
          首页
        </a>
      
    
      
        <a href="civil3d" class="menu">
          Civil3D
        </a>
      
    
      
        <a href="arcgis" class="menu">
          ArcGIS
        </a>
      
    
      
        <a href="/archives" class="menu">
          归档
        </a>
      
    
      
        <a href="/tags" class="menu">
          标签
        </a>
      
    
      
        <a href="/post/about" class="menu">
          关于
        </a>
      
    
  </div>
  <div class="social-container">
    
      
    
      
    
      
    
      
    
      
    
  </div>
</div>

        <div class="post-detail">
          <article class="post">
            <h2 class="post-title">
              Civil3D API定义多视图快（Multiview Block）
            </h2>
            <div class="post-info">
              <span>
                2020-09-15
              </span>
              <span>
                2 min read
              </span>
              
            </div>
            
            <div class="post-content-wrapper">
              <div class="post-content">
                <p>Multiview Block是Autocad Architecture中的概念。</p>
<pre><code class="language-C#">[CommandMethod(&quot;DEFINEMVBLOCK&quot;)]
public void DefineMVBlock()
{
	Document acDoc = Autodesk.AutoCAD.ApplicationServices.Core.Application.DocumentManager.MdiActiveDocument;

	using (Transaction trans = acDoc.Database.TransactionManager.StartTransaction())
	{
        BlockTable acBlkTbl;
        acBlkTbl = trans.GetObject(acDoc.Database.BlockTableId, OpenMode.ForRead) as BlockTable;
        
        ObjectId blk1 = acBlkTbl[&quot;tree_2d&quot;];
        ObjectId blk_3d = acBlkTbl[&quot;tree_3d&quot;];
        Aecdb.DisplayRepresentation displayRep_2d = new Aecdb.DisplayRepresentation();
        Aecdb.DisplayRepresentation displayRep_3d = new Aecdb.DisplayRepresentation();
        
        ObjectIdCollection oids = Aecdb.DisplayRepresentationManager.GetActiveDisplayRepresentationSets(acDoc.Database);                
        foreach (ObjectId id in oids)
        {
            Aecdb.DisplaySet ds = trans.GetObject(id,OpenMode.ForRead) as Aecdb.DisplaySet;
            foreach(ObjectId drid in ds.DisplayRepresentationIds )
            {
                Aecdb.DisplayRepresentation disp = trans.GetObject(drid,OpenMode.ForRead) as Aecdb.DisplayRepresentation;
                if (disp.Name == &quot;AecDbDispRepMvBlockRef&quot;) displayRep_2d = disp;
                if (disp.Name == &quot;AecDbDispRepMvBlockRefModel&quot;) displayRep_3d = disp;
            }
        }
        
        Aecdb.MultiViewBlockViewDefinition mvblockViewDef_2d = new Aecdb.MultiViewBlockViewDefinition();
        mvblockViewDef_2d.SetViewOn(Aecdb.ViewDirection.Top, true); 
        mvblockViewDef_2d.BlockId = blk1;
        Aecdb.MultiViewBlockDisplayRepresentationDefinition mvblockRepDef_2d = new Aecdb.MultiViewBlockDisplayRepresentationDefinition();
        mvblockRepDef_2d.ViewDefinitions.Add(mvblockViewDef_2d);
        mvblockRepDef_2d.DisplayRepresentationId = displayRep_2d.Id;
        
        Aecdb.MultiViewBlockViewDefinition mvblockViewDef_3d = new Aecdb.MultiViewBlockViewDefinition();
        mvblockViewDef_3d.SetAllViews(true);
        mvblockViewDef_3d.BlockId = blk_3d;
        Aecdb.MultiViewBlockDisplayRepresentationDefinition mvblockRepDef_3d = new Aecdb.MultiViewBlockDisplayRepresentationDefinition();
        mvblockRepDef_3d.ViewDefinitions.Add(mvblockViewDef_3d);
        mvblockRepDef_3d.DisplayRepresentationId = displayRep_3d.Id;
                
        Aecdb.MultiViewBlockDefinition mvblockDef = new Aecdb.MultiViewBlockDefinition();
        mvblockDef.DisplayRepresentationDefinitions.Add(mvblockRepDef_2d);
        mvblockDef.DisplayRepresentationDefinitions.Add(mvblockRepDef_3d);

        mvblockDef.Description = &quot;This is a MVBlock defined by Net API.&quot;;

        Aecdb.DictionaryMultiViewBlockDefinition mvblockDic = new Aecdb.DictionaryMultiViewBlockDefinition(acDoc.Database);
        
        mvblockDic.AddNewRecord(&quot;MyMVBlock&quot;,mvblockDef);
        trans.Commit();
    }
 }
</code></pre>

              </div>
              <div class="toc-container">
                
              </div>
            </div>
          </article>
        </div>

        
          <div class="next-post">
            <div class="next">下一篇</div>
            <a href="https://xiaoxiong314.github.io/post/hello-gridea/">
              <h3 class="post-title">
                Hello Gridea
              </h3>
            </a>
          </div>
        

        

        <div class="site-footer">
  Powered by <a href="https://github.com/getgridea/gridea" target="_blank">Gridea</a>
  <a class="rss" href="https://xiaoxiong314.github.io/atom.xml" target="_blank">
    <i class="ri-rss-line"></i> RSS
  </a>
</div>

      </div>
    </div>

    <script>
      hljs.initHighlightingOnLoad()

      let mainNavLinks = document.querySelectorAll(".markdownIt-TOC a");

      // This should probably be throttled.
      // Especially because it triggers during smooth scrolling.
      // https://lodash.com/docs/4.17.10#throttle
      // You could do like...
      // window.addEventListener("scroll", () => {
      //    _.throttle(doThatStuff, 100);
      // });
      // Only not doing it here to keep this Pen dependency-free.

      window.addEventListener("scroll", event => {
        let fromTop = window.scrollY;

        mainNavLinks.forEach((link, index) => {
          let section = document.getElementById(decodeURI(link.hash).substring(1));
          let nextSection = null
          if (mainNavLinks[index + 1]) {
            nextSection = document.getElementById(decodeURI(mainNavLinks[index + 1].hash).substring(1));
          }
          if (section.offsetTop <= fromTop) {
            if (nextSection) {
              if (nextSection.offsetTop > fromTop) {
                link.classList.add("current");
              } else {
                link.classList.remove("current");    
              }
            } else {
              link.classList.add("current");
            }
          } else {
            link.classList.remove("current");
          }
        });
      });

    </script>
  </body>
</html>
